name: ditonton
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.8.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_rating_bar: ^4.0.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  mocktail: ^0.3.0
  path_provider: ^2.0.2
  provider: ^6.0.3
  sqflite: ^2.0.0+3

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8

flutter:

  uses-material-design: true

  assets:
    - assets/
    - certificates/
